title: Shintia Azzahra # your name (or website title) here
logo: "Images/headshot 7.jpg?raw=true" # your photo (or logo) here
description:
  # your text below (remove <br> elements if you don't need line breaks)
  <strong>Electrical Enginnering</strong>
  <br><br>
  Self-motivated, curious, diligent, and goal-oriented Data Scientist eager to apply my Python skills to solve business problems. With a background in science, I bring over 8 years of analytical thinking, data analysis, attention to detail and problem solving to the table.
  <br><br>

  <a href="www.linkedin.com/in/shintiaazzahra/">View My LinkedIn Profile</a> ||
  <a href="https://github.com/shintiaazzahra">View My Github Profile</a>

theme: jekyll-theme-minimal
# google_analytics: G-69MVL0BC84 # your Google Analytics tracking ID here
